use_frameworks!

platform :ios, '9.0'

target 'LJFastDeveloper_Example' do
  pod 'LJFastDeveloper/Leaks', :path => '../'
  pod 'LJFastDeveloper', :path => '../'
  pod 'LJFastDeveloper/App', :path => '../'

  target 'LJFastDeveloper_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
